# Generated by Django 4.0 on 2021-12-27 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('spotify_uri', models.SlugField(unique=True)),
                ('spotify_type', models.CharField(choices=[('AR', 'artist'), ('AL', 'album'), ('TR', 'track'), ('SH', 'show'), ('EP', 'episode')], max_length=2)),
                ('image_path', models.SlugField(null=True)),
                ('preview_path', models.SlugField(null=True)),
                ('observers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
