# Generated by Django 4.0 on 2022-01-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_code',
            field=models.SlugField(max_length=256),
        ),
        migrations.AlterField(
            model_name='game',
            name='task_id',
            field=models.SlugField(max_length=256),
        ),
    ]
