# Generated by Django 4.0 on 2021-12-28 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0002_stage_scoreboard_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='spotify_assert',
            new_name='spotify_asset',
        ),
    ]
