# Generated by Django 4.0 on 2021-12-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0003_rename_spotify_assert_choice_spotify_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='task_id',
            field=models.SlugField(default=True, max_length=32),
            preserve_default=False,
        ),
    ]
