# Generated by Django 4.0 on 2021-12-29 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play_api', '0002_playerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerprofile',
            old_name='user',
            new_name='player',
        ),
    ]
