# Generated by Django 4.0 on 2022-01-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_api', '0003_rename_user_playerprofile_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='biggest_gainer',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='biggest_loser',
            field=models.BigIntegerField(null=True),
        ),
    ]
