# Generated by Django 4.0 on 2022-01-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_api', '0004_playerprofile_biggest_gainer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='biggest_gainer',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='biggest_loser',
            field=models.BigIntegerField(default=0),
        ),
    ]
