# Generated by Django 4.0 on 2022-01-04 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0002_alter_game_game_code_alter_game_task_id'),
        ('play_api', '0005_alter_playerprofile_biggest_gainer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game_api.game'),
        ),
    ]
