# Generated by Django 4.0 on 2021-12-27 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.SlugField(unique=True)),
                ('occupation', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50, null=True)),
                ('bio', models.TextField(null=True)),
                ('twitter', models.SlugField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
