# Generated by Django 4.0 on 2022-01-04 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('display_name', models.SlugField(max_length=256, null=True)),
                ('image', models.SlugField(max_length=256, null=True)),
                ('occupation', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256, null=True)),
                ('bio', models.TextField(null=True)),
                ('twitter', models.SlugField(max_length=256, null=True)),
                ('data_loaded', models.BooleanField(default=False)),
            ],
        ),
    ]
