# Generated by Django 4.0 on 2021-12-27 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0002_rename_avatar_url_profile_image_remove_profile_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='country',
        ),
    ]
