# Generated by Django 4.0 on 2021-12-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0003_rename_location_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
