# Generated by Django 4.0 on 2022-01-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0004_profile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='data_loaded',
            field=models.BooleanField(default=False),
        ),
    ]
