# Generated by Django 4.0 on 2022-01-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0005_profile_data_loaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.SlugField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.SlugField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.SlugField(max_length=256, null=True),
        ),
    ]
