# Generated by Django 4.0 on 2022-01-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0006_alter_profile_country_alter_profile_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.SlugField(max_length=256, null=True),
        ),
    ]
