version: '3.9'

services:
  web:
    container_name: topsifyle
    build:
      context: .
      dockerfile: web.dockerfile
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  certbot:
    container_name: certbot_web
    image: certbot/certbot

    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
